<<<<<<< HEAD
services:
  - type: web
    name: lovewaving
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate --schema=./prisma/schema.prisma && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lovewaving-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: lovewaving
          type: web
          property: host

databases:
  - name: lovewaving-db
    plan: free
    databaseName: lovewaving
    user: lovewaving

=======
services:
  - type: web
    name: lovewaving
    env: node
    plan: free
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: lovewaving-db
          property: connectionString
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: NEXTAUTH_URL
        fromService:
          name: lovewaving
          type: web
          property: host

databases:
  - name: lovewaving-db
    plan: free
    databaseName: lovewaving
    user: lovewaving

>>>>>>> 323292e4b68c097df3b7c68f2edcdaab42bcfef9
